version: "3.9"
services:
  api:
    build: ./api
    # env_file:
    #   - ".env"
    ports: 
      - 8080:8080
    networks:
      - default
  app:
    build: ./app
    ports:
      - 80:80
    networks:
      - default

volumes:
  pg_db: